In [2]:
import torch



In [3]:
t1 = torch.tensor([1, 2], dtype = torch.float32)


In [4]:
t1*=t1
t1*=.7
t1

tensor([0.7000, 2.8000])

In [6]:

x = torch.empty(2, 3).normal_(mean =0, std = 1)

x


tensor([[ 0.0348,  1.5530,  0.8858],
        [-0.8387,  0.3401,  0.0086]])

In [10]:

torch.manual_seed(42)
torch.diag(torch.rand(3))


tensor([[0.8823, 0.0000, 0.0000],
        [0.0000, 0.9150, 0.0000],
        [0.0000, 0.0000, 0.3829]])

In [11]:
t1 = torch.tensor([2, 4, 12])
t2 = torch.tensor([1, 8, 6])

t3 = t1 / t2
t3

tensor([2.0000, 0.5000, 2.0000])

In [12]:
t1 = torch.tensor([ [1, 2], [3, 4] ])
t2 = torch.tensor([ [2, 1], [1, 1] ])

t3 = t1.mm(t2)

t3

tensor([[ 4,  3],
        [10,  7]])

In [13]:
batch = 32
n, m, p = 3, 6, 4

t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))

t3 = t1.bmm(t2)

t3


tensor([[[1.7644, 1.9331, 1.5801, 1.8002],
         [2.4931, 1.5030, 2.0185, 1.4013],
         [1.6951, 1.5507, 1.3283, 1.4309]],

        [[0.8246, 0.9196, 1.3100, 1.1013],
         [1.0488, 1.5650, 0.8555, 1.1995],
         [1.7890, 1.6118, 1.7242, 1.4421]],

        [[1.8680, 1.2493, 1.3656, 2.3154],
         [1.0251, 1.0352, 1.1093, 1.2110],
         [1.5991, 0.8159, 0.9095, 1.8163]],

        [[1.9894, 1.9803, 1.3295, 1.2066],
         [1.9569, 1.6096, 1.2082, 1.2421],
         [2.2879, 1.4109, 1.2444, 1.2639]],

        [[1.9459, 1.1847, 2.1422, 1.1326],
         [1.9270, 1.7609, 2.1262, 1.1161],
         [1.8318, 1.4232, 2.0940, 0.8966]],

        [[2.0873, 1.8808, 0.6543, 1.6690],
         [1.0677, 0.8151, 0.8295, 1.2522],
         [0.8734, 0.7369, 0.9821, 0.9984]],

        [[1.6201, 0.5881, 0.9546, 1.8227],
         [1.2874, 0.4309, 0.6409, 1.4183],
         [1.4577, 0.3538, 0.6639, 1.5016]],

        [[1.0441, 0.7800, 2.3401, 2.0697],
         [0.8293, 0.3834, 1.5513, 1.2466

# Broadcasting

In [14]:
t1 = torch.ones((3, 4))* 5
t1 -= torch.ones((1, 4))

t1

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [18]:

t = torch.tensor([
    [20, 2],
    [100, 53]
])

values, indices = torch.max(t, dim = 0)


print(values)
print(indices)


tensor([100,  53])
tensor([1, 1])


In [19]:
t = torch.rand(size=(3, 4))

t

tensor([[0.6701, 0.0616, 0.4221, 0.4889],
        [0.2974, 0.6820, 0.5322, 0.8510],
        [0.4556, 0.1844, 0.8533, 0.5698]])

In [20]:
values_y, indices = torch.sort(t, dim = 0, descending = False)
print(values_y)
print(indices)

tensor([[0.2974, 0.0616, 0.4221, 0.4889],
        [0.4556, 0.1844, 0.5322, 0.5698],
        [0.6701, 0.6820, 0.8533, 0.8510]])
tensor([[1, 0, 0, 0],
        [2, 2, 1, 2],
        [0, 1, 2, 1]])


In [21]:
t.clamp(min=0.2, max=0.4)

tensor([[0.4000, 0.2000, 0.4000, 0.4000],
        [0.2974, 0.4000, 0.4000, 0.4000],
        [0.4000, 0.2000, 0.4000, 0.4000]])

In [23]:
torch.any(t>.8)

tensor(True)

In [24]:
5

5

In [163]:
t

tensor([[0.8654, 0.7074, 0.1055, 0.6454],
        [0.9819, 0.1698, 0.5380, 0.6429],
        [0.3200, 0.8291, 0.9446, 0.9867]])

In [25]:
t2 = torch.where(t>=.5, 1, 0)
t2

tensor([[1, 0, 0, 0],
        [0, 1, 1, 1],
        [0, 0, 1, 1]])